--DDL(DATA DEFINITION LANGUAGE)--

CREATE DATABASE filmes;

USE filmes;


-- NOT NULL -> SERVE PARA OBRIGAR O USUARIO A DEFINIR UM DADO --
CREATE TABLE generos
(
	IdGenero	INT PRIMARY KEY IDENTITY,
	NOME		VARCHAR(200) NOT NULL
);

-- É NECESSARIO COLOCAR O REFECENCES QUANDO SE TRATA DE FOREIGN KEY--
CREATE TABLE filmes
(
	IdFilme		INT PRIMARY KEY IDENTITY,
	IdGenero	INT	FOREIGN KEY REFERENCES generos(IdGenero),
	TITULO		VARCHAR(200) NOT NULL
);