CREATE DATABASE PESSOA;

CREATE TABLE CNH
(
	IdCNH INT PRIMARY KEY IDENTITY,
	NumCNH VARCHAR(11)
);

CREATE TABLE CONTATOS
(
	IdCONTATO INT PRIMARY KEY IDENTITY,
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR(100)
);

CREATE TABLE PESSOAS
(
	IdPESSOA INT PRIMARY KEY IDENTITY,
	IdCNH Int foreign key references CNH(IdCNH),
	IdCONTATO Int foreign key references CONTATOS(IdCONTATO),

	NOME VARCHAR(100),
	CPF VARCHAR(11),
	ALTURA VARCHAR(3),
	TELEFONE VARCHAR(5),
	DATADENASCIMENTO VARCHAR(6),
);