USE pessoa;

SELECT * FROM pessoa;
SELECT * FROM CNH;
SELECT * FROM EMAILS;
SELECT * FROM TELEFONE;

SELECT * FROM pessoa ORDER BY NOME DESC;
SELECT * FROM CNH ORDER BY NUMEROCNH DESC;
SELECT * FROM EMAILS ORDER BY EMAIL DESC;
SELECT * FROM TELEFONE ORDER BY NUMERO DESC;

