USE clinica;

INSERT INTO CLINICA(CNPJ, ENDEREÇO)
VALUES			(12345, 'RUA 3');

INSERT INTO DONO(NOME, CPF)
VALUES			('GUILHERME', 56789);

INSERT INTO TIPO(NOME)
VALUES			('GOLDEN');

INSERT INTO RAÇA(IDTIPO, NOME)
VALUES			(1, 'BILLY');

INSERT INTO PET(IdDONO, IdRAÇA, NOME, NASCIMENTO)
VALUES			(1, 1, 'BILLY', 2010);

INSERT INTO VETERINARIO(IdCLINICA, NOME, CRMV)
VALUES			(1, 'PETZ', 246810);

INSERT INTO ATENDIMENTO(IdVETERINARIO, IdPET, NOME, DATA_DE_ATENDIMENTO)
VALUES			(1, 1, 'CONSULTA', 2021);